# Generated by Django 5.1.4 on 2025-01-06 12:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.BooleanField(choices=[(True, 'Entrance'), (False, 'Exit')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='security_hub.scanlog'),
        ),
    ]
