# Generated by Django 5.1.4 on 2025-01-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_hub', '0002_scanlog_worker_active_worker_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='card',
            field=models.CharField(max_length=100),
        ),
    ]
