# Generated by Django 5.1.4 on 2025-01-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_hub', '0003_alter_scanlog_card_alter_worker_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='scan',
        ),
        migrations.AddField(
            model_name='scanlog',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scanlog', to='security_hub.worker'),
        ),
    ]
