# Generated by Django 5.1.4 on 2025-01-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_hub', '0005_remove_scanlog_type_scanlog_scan_result_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['-timestamp'], name='security_hu_timesta_f7c946_idx'),
        ),
    ]
